### ISSUE TITLE
Laptop shuts down

### ISSUE THREAD

**Issue by LIONNNNNN** [ZoR3oL/t490-hackintosh#3]
Hi,

i created a Boot disk like the Dorthin Guide with an Mac.
I copied the boot and oc folder into my efi folder on my usb drive.

When i boot from the usb drive i can select install Monterey, after that i get the apple logo and after 10seconds the laptop shuts down.

Any Idea?

**Comment by LIONNNNNN** [comment]
[opencore-2022-04-04-203449.txt](https://github.com/ZoR3oL/t490-hackintosh/files/8412258/opencore-2022-04-04-203449.txt)

**Comment by ZoR3oL** [comment]
Hi.

Which hard drive do you have into your laptop? Is it a samsung p981?

**Comment by LIONNNNNN** [comment]
Hi,

no the WDC PC SN720

**Comment by LIONNNNNN** [comment]
[opencore-2022-04-05-181142.txt](https://github.com/ZoR3oL/t490-hackintosh/files/8419958/opencore-2022-04-05-181142.txt)

**Comment by LIONNNNNN** [comment]
I edited the config.plist but the same error.

**Comment by LIONNNNNN** [comment]
It was my fault, i had CSM enabled in the BIOS.

**Comment by ZoR3oL** [comment]
Glad to see that you have found the issue.
I'll add this point into the README.md
Have fun :)
